[package]
name = "wargod"
version = "0.1.0"
authors = ["Philip Woods <elzairthesorcerer@gmail.com>"]

[dependencies]
rayon    = "0.8"
num_cpus = "1.0"
memmap   = "0.5"
nalgebra = "0.12"
ncollide = "0.12"
dacite = "0.6.1"
dacite-winit = "0.6.0"
winit = "0.7"
glsl-to-spirv-macros = "0.1"
glsl-to-spirv-macros-impl = "0.1"